### ISSUE TITLE
Script for training and generation to run locally?

### ISSUE THREAD

**Issue by SoftologyPro** [Beinabih/Unconditional-MusicGen-Trainer#3]
Could you please provide complete working scripts for training and generation from a model once trained?

Running this script

```
from train import main

dataset_cfg = dict(
        dataset_path_train = "train",
        dataset_path_eval = "eval",
        batch_size=4,
        num_examples_train= 1000,
        num_examples_eval= 200,
        segment_duration= 30,
        sample_rate= 32_000,
        shuffle= True,
        return_info= False)

cfg = dict(
    learning_rate = 0.0001,
    epochs = 80,
    model = "small",
    seed = (hash("blabliblu") % 2**32 - 1),
    use_wandb = True
)

main("Model Name", cfg, dataset_cfg, 'Wandb Project Name')
```

Gives these errors.  This is Windows so Triton can be ignored.

```
(venv) D:\Tests\Unconditional-MusicGen-Trainer>python do_training.py
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose "Don't visualize my results"
wandb: Tracking run with wandb version 0.16.6
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\audiocraft\models\musicgen.py:127: UserWarning: MusicGen pretrained model relying on deprecated checkpoint mapping. Please use full pre-trained id instead: facebook/musicgen-small
  warnings.warn(
D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
  0%|          | 0/80 [00:00<?, ?it/s]
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose "Don't visualize my results"
wandb: Tracking run with wandb version 0.16.6
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\audiocraft\models\musicgen.py:127: UserWarning: MusicGen pretrained model relying on deprecated checkpoint mapping. Please use full pre-trained id instead: facebook/musicgen-small
  warnings.warn(
D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\nn\utils\weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
  0%|          | 0/80 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Python\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Python\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Tests\Unconditional-MusicGen-Trainer\do_training.py", line 22, in <module>
    main("Model Name", cfg, dataset_cfg, 'Wandb Project Name')
  File "D:\Tests\Unconditional-MusicGen-Trainer\train.py", line 199, in main
    current_step = train(
  File "D:\Tests\Unconditional-MusicGen-Trainer\train.py", line 52, in train
    for _, batch in enumerate(dataloader):
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1040, in __init__
    w.start()
  File "D:\Python\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Python\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Python\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "D:\Python\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Python\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\Python\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "D:\Python\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Tests\Unconditional-MusicGen-Trainer\do_training.py", line 22, in <module>
    main("Model Name", cfg, dataset_cfg, 'Wandb Project Name')
  File "D:\Tests\Unconditional-MusicGen-Trainer\train.py", line 199, in main
    current_step = train(
  File "D:\Tests\Unconditional-MusicGen-Trainer\train.py", line 52, in train
    for _, batch in enumerate(dataloader):
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1295, in _get_data
    success, data = self._try_get_data()
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1146, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 26144) exited unexpectedly
Traceback (most recent call last):
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "D:\Python\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Tests\Unconditional-MusicGen-Trainer\do_training.py", line 22, in <module>
    main("Model Name", cfg, dataset_cfg, 'Wandb Project Name')
  File "D:\Tests\Unconditional-MusicGen-Trainer\train.py", line 199, in main
    current_step = train(
  File "D:\Tests\Unconditional-MusicGen-Trainer\train.py", line 52, in train
    for _, batch in enumerate(dataloader):
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1295, in _get_data
    success, data = self._try_get_data()
  File "D:\Tests\Unconditional-MusicGen-Trainer\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1146, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 26144) exited unexpectedly
wandb: You can sync this run to the cloud by running: MB)
wandb: wandb sync D:\Tests\Unconditional-MusicGen-Trainer\wandb\offline-run-20240405_184312-8r4bifds
wandb: Find logs at: .\wandb\offline-run-20240405_184312-8r4bifds\logs
wandb: You can sync this run to the cloud by running:
wandb: wandb sync D:\Tests\Unconditional-MusicGen-Trainer\wandb\offline-run-20240405_184342-334ah70z
wandb: Find logs at: .\wandb\offline-run-20240405_184342-334ah70z\logs
```

I have a bunch of mp3 files under train and eval ready to go.

**Comment by dillfrescott** [comment]
Does the same for me and crashes. Looks like it might be borked
